/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react' // 🛠 useState, useEffect 추가
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./room.glb')
  
  // 어떤 가구에 마우스가 올라갔는지 저장하는 상태 ('TV', 'Laptop', 또는 null)
  const [hovered, setHovered] = useState(null)

  // 마우스 커서 스타일 관리
  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto'
  }, [hovered])

  return (
    <group {...props} dispose={null}>
      {/* --- TV 가구 --- */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TVLow.geometry}
        // 호버 시 기존 재질 위에 emissive(자체 발광) 효과 적용
        material={materials['Material.002']}
        position={[-16.451, 0.497, -5.909]}
        rotation={[0, -0.297, 0]}
        scale={8.586}
        onClick={(e) => { 
          e.stopPropagation(); 
          props.onSelectFurniture('TV'); 
        }}
        onPointerOver={(e) => { 
          e.stopPropagation(); 
          setHovered('TV'); 
        }}
        onPointerOut={() => setHovered(null)}
      >
        {/* 호버 시 가구 전체가 반투명한 흰색으로 은은하게 빛남 */}
        {hovered === 'TV' && (
          <meshStandardMaterial 
            {...materials['Material.002']} 
            emissive="white" 
            emissiveIntensity={0.5} // 빛의 세기 (0.1 ~ 1.0 사이로 조절 가능)
            transparent
            opacity={0.9}
          />
        )}
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.closet.geometry}
        material={materials.Material_25}
        position={[-11.907, 5.619, -17.452]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />

      {/* --- Laptop 그룹 --- */}
      <group position={[-7.459, 1.483, -8.362]} rotation={[1.697, -0.23, 2.079]} scale={0.708}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Material006_0.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Material006_0_1.geometry}
          material={materials['Material.005']}
          onClick={(e) => { 
            e.stopPropagation(); 
            props.onSelectFurniture('Laptop'); 
          }}
          onPointerOver={(e) => { 
            e.stopPropagation(); 
            setHovered('Laptop'); 
          }}
          onPointerOut={() => setHovered(null)}
        >
          {/* 노트북 클릭 가능 부분 호버 효과 */}
          {hovered === 'Laptop' && (
            <meshStandardMaterial 
              {...materials['Material.005']} 
              emissive="white" 
              emissiveIntensity={0.5}
              transparent
              opacity={0.9}
            />
          )}
        </mesh>
      </group>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.low_table.geometry}
        material={materials.Material_25}
        position={[-6.022, 2.953, -8.833]}
        rotation={[-Math.PI / 2, 0, 0.786]}
        scale={[0.07, 0.074, 0.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sofa.geometry}
        material={materials['Scene_-_Root']}
        position={[-15.264, -0.992, -14.459]}
        rotation={[-Math.PI / 2, 0, 0.604]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.wallpaper1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_1.geometry}
        material={materials.floor}
      />
    </group>
  )
}

useGLTF.preload('./room.glb')