/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TVLow.geometry}
        material={materials['Material.002']}
        position={[-16.451, 0.497, -5.909]}
        rotation={[0, -0.297, 0]}
        scale={8.586}
        onClick={(e) => { e.stopPropagation(); props.onSelectFurniture('TV'); }}
  onPointerOver={() => (document.body.style.cursor = 'pointer')}
  onPointerOut={() => (document.body.style.cursor = 'auto')}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.closet.geometry}
        material={materials.Material_25}
        position={[-11.907, 5.619, -17.452]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <group position={[-7.459, 1.483, -8.362]} rotation={[1.697, -0.23, 2.079]} scale={0.708}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Material006_0.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Material006_0_1.geometry}
          material={materials['Material.005']}
          onClick={(e) => { e.stopPropagation(); props.onSelectFurniture('Laptop'); }}
  onPointerOver={() => (document.body.style.cursor = 'pointer')}
  onPointerOut={() => (document.body.style.cursor = 'auto')}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.low_table.geometry}
        material={materials.Material_25}
        position={[-6.022, 2.953, -8.833]}
        rotation={[-Math.PI / 2, 0, 0.786]}
        scale={[0.07, 0.074, 0.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sofa.geometry}
        material={materials['Scene_-_Root']}
        position={[-15.264, -0.992, -14.459]}
        rotation={[-Math.PI / 2, 0, 0.604]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.wallpaper1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_1.geometry}
        material={materials.floor}
      />
    </group>
  )
}

useGLTF.preload('/room.glb')